### ISSUE TITLE
Assets TODO list #1

### ISSUE THREAD

**Issue by matshou** [yooksi/cities-skylines-traffic-assets#1]
- [x] BUNDESSTRAßE Autobahnauffahrt 2L
- [x] BUNDESSTRAßE Autobahnauffahrt 2R
- [x] BUNDESSTRAßE 1Sp-1GR
- [x] BUNDESSTRAßE GLR
- [x] BUNDESSTRAßE Kreisverkehr 4A
- [x] BUNDESSTRAßE PfeilKleinStadtL
- [x] BUNDESSTRAßE PfeilKleinStadtR
- [x] BUNDESSTRAßE PfeilKleinBundess EL
- [x] BUNDESSTRAßE PfeilKleinBundess ER
- [x] BUNDESSTRAßE PfeilKleinAutob EL
- [x] BUNDESSTRAßE GL Ank
- [x] BUNDESSTRAßE GLR Ank
- [x] BUNDESSTRAßE GR Ank

[Original asset pack on Steam](http://steamcommunity.com/sharedfiles/filedetails/?id=1178771213)
